type_img: "image/jpeg,image/gif,image/png"
per_page: 8
per_page_users: 3
multiple: 0
single: 1
status:
  exam:
    start: "start"
    testing: "testing"
    uncheck: "uncheck"
    checked: "checked"
    inactive: "inactive"
exams:
  default_mark: 0
  default_correct: false
  number_question: 30
  duaration: 20
question_number: 30
